default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: <%= Rails.application.credentials.dig(:postgresql, :username) %>
  password: <%= Rails.application.credentials.dig(:postgresql, :password) %>
  host: localhost
  database: bakery
